### ISSUE TITLE
Compatibility with SmartMoving/(Render)PlayerAPI

### ISSUE THREAD

**Issue by vico93** [unascribed/Backlytra#2]
Hi!

First thing first, thank you so much for this awesome backport!

But i'm having issues using Backlytra with SmartMoving.

When i try to use an elytra with [SmartMoving](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1274224-smart-moving)/[PlayerAPI](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1277996-player-api) installed (with [RenderPlayerAPI and RenderPlayerAPIEnchancer](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1283669-render-player-api) installed or not), it dont stick behind the player:

![2016-06-18_18 21 33](https://cloud.githubusercontent.com/assets/3485505/16173780/15742db2-3583-11e6-94a9-1cc96f78320e.png)

And the animation. [ohh](https://www.youtube.com/watch?v=4IhyP6lVG6Y)...

Other thing: while without SmartMoving, in creative mode, when i press space twice to fall the Elytra is acioned automatically, with SM it doesnt ocour (due to SM flying animation?) and i need to press space again to activate that funky flying.

Is possible to fix something in your side (given SM author is "dead") or i really need to remove SM to get the mod working?

**Comment by exaskye** [comment]
I'm honestly not sure what you were expecting to happen with something that hooks so deeply into the movement logic. There's not much I can do about this.

**Comment by vico93** [comment]
Yeah. I see i've typo the title. In fact i would suggest (if possible) a compatibility with PlayerAPI.

But if you says its not possible (plus SmartMoving semidead), i'm removing SmartMoving/PlayerAPI for now.

Besides that, SM gives me several errors with other mods, so (for my side) removing is the best solution. But i dont sure about others.

Anyway, closing (wontfix?)
