### ISSUE TITLE
2 Elytras in 3rd person view

### ISSUE THREAD

**Issue by Nicholas32704** [unascribed/Backlytra#5]
I have recently installed this mod, and it seems to work perfectly. The mechanics and sounds of the Elytra are amazingly identical to the original 1.9 Ellytra, however I recently discovered that upon entering the 3rd person view, whenever you fly with the Elytra it seems to generate a 2nd one a few blocks beneath the player. It glides back to the Elytra on the player's back whenever you stop flying, however.

Here's a screenshot of what it looks like:

![2017-10-12_18 38 24](https://user-images.githubusercontent.com/32754193/31525514-144d0fc8-af7e-11e7-8dfc-f08be8de89a7.png)
![2017-10-12_18 48 24](https://user-images.githubusercontent.com/32754193/31525515-14676cce-af7e-11e7-90be-5dbb2ce146b3.png)
![2017-10-12_18 48 35](https://user-images.githubusercontent.com/32754193/31525517-14826f24-af7e-11e7-8512-81aaa9ffcbbe.png)
![2017-10-12_18 48 45](https://user-images.githubusercontent.com/32754193/31525518-149b26ea-af7e-11e7-9377-94ec13207dae.png)
![2017-10-12_18 48 53](https://user-images.githubusercontent.com/32754193/31525520-14b47d0c-af7e-11e7-9abe-288f8f2c5028.png)

Is this a known bug?

**Comment by exaskye** [comment]
This mod is EOL (end-of-life), but I can help you troubleshoot, as I've never seen this. If it winds up being a bug in the mod, I won't be fixing it, sorry.

What's your Minecraft version (and mod list)?

(And they're amazingly similar because I literally copy-pasted the vanilla 1.9 Elytra code. This is also why it's my only mod that is All Rights Reserved instead of MIT.)

**Comment by Nicholas32704** [comment]
I'm using modded minecraft 1.7.10 with OptiFine and 60+ other mods (too many to list, but the APIs and libraries include Farseek, Bookshelf, IChun Util, Gilded Games Util, Animation Api, Brewing Api, etc, along with OptiFine.)

I use Minecraft Forge 10.13.4.1614 for Minecraft 1.7.10, along with FML v7.10.99.99

Does this help?

**Comment by exaskye** [comment]
Animation API is a potential culprit. You can shortcut sending me a modlist by forcing a crash by holding F3+C for 10 seconds while ingame and sending me the crash report, it contains a mod list.

**Comment by Nicholas32704** [comment]
Ah ok.

Also it apparently happens to the gloves in Aether II as well:

![2017-10-12_19 57 54](https://user-images.githubusercontent.com/32754193/31527746-a2c6c9a2-af8c-11e7-80e8-0ed75fb15759.png)

**Comment by Nicholas32704** [comment]
Anyways here's the crash report:

---- Minecraft Crash Report ----
// My bad.

Time: 10/12/17 8:34 PM
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['KrazyMan101'/463, l='MpServer', x=-222.08, y=62.62, z=303.68]]
	Chunk stats: MultiplayerChunkCache: 287, 296
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-224,64,240), Chunk: (at 0,4,0 in -14,15; contains blocks -224,0,240 to -209,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 10314 game time, 10314 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 125 total; [EntitySkeleton['Skeleton'/256, l='MpServer', x=-221.50, y=53.00, z=276.50], EntitySquid['Squid'/257, l='MpServer', x=-225.24, y=59.78, z=284.59], EntitySheep['Sheep'/258, l='MpServer', x=-225.72, y=64.00, z=279.41], EntitySheep['Sheep'/259, l='MpServer', x=-224.59, y=64.00, z=280.66], EntityZombie['Zombie'/260, l='MpServer', x=-222.34, y=31.00, z=283.25], EntityBat['Bat'/261, l='MpServer', x=-189.54, y=21.84, z=316.83], EntitySquid['Squid'/262, l='MpServer', x=-223.34, y=59.97, z=289.93], EntityZombie['Zombie'/278, l='MpServer', x=-205.50, y=22.00, z=264.50], EntityZombie['Zombie'/279, l='MpServer', x=-203.50, y=22.00, z=265.50], EntityBat['Bat'/280, l='MpServer', x=-205.47, y=22.00, z=264.25], EntityBat['Bat'/281, l='MpServer', x=-205.50, y=22.00, z=264.25], EntityPluckableChicken['entity.Pluckable Chicken.name'/282, l='MpServer', x=-204.63, y=67.00, z=267.59], EntityPluckableChicken['entity.Pluckable Chicken.name'/283, l='MpServer', x=-192.44, y=79.00, z=268.69], EntityTrail['unknown'/540, l='MpServer', x=-222.08, y=62.62, z=303.68], EntityPig['Pig'/299, l='MpServer', x=-184.22, y=69.00, z=238.34], EntityPluckableChicken['entity.Pluckable Chicken.name'/300, l='MpServer', x=-190.66, y=79.00, z=268.44], EntityPig['Pig'/301, l='MpServer', x=-182.75, y=80.00, z=263.41], EntityPig['Pig'/302, l='MpServer', x=-184.88, y=79.00, z=273.84], EntityMobEnderman['Enderman'/303, l='MpServer', x=-176.56, y=22.00, z=318.63], EntityCreeper['Creeper'/304, l='MpServer', x=-176.69, y=21.00, z=317.69], EntityPig['Pig'/305, l='MpServer', x=-186.34, y=72.00, z=379.75], EntityPig['Pig'/306, l='MpServer', x=-180.81, y=72.00, z=377.81], EntityPig['Pig'/307, l='MpServer', x=-176.50, y=74.00, z=376.50], EntityPig['Pig'/308, l='MpServer', x=-176.50, y=74.00, z=376.50], EntitySkeleton['Skeleton'/316, l='MpServer', x=-174.50, y=27.00, z=233.56], EntityZombie['Zombie'/317, l='MpServer', x=-173.47, y=27.00, z=235.50], EntityCreeper['Creeper'/318, l='MpServer', x=-173.31, y=25.00, z=232.47], EntityCreeper['Creeper'/319, l='MpServer', x=-172.09, y=25.00, z=235.50], EntityPig['Pig'/320, l='MpServer', x=-166.75, y=64.00, z=231.97], EntityCreeper['Creeper'/321, l='MpServer', x=-165.50, y=43.00, z=245.00], EntityPig['Pig'/322, l='MpServer', x=-165.97, y=85.00, z=249.50], EntityPig['Pig'/323, l='MpServer', x=-173.31, y=85.00, z=265.50], EntitySkeleton['Skeleton'/324, l='MpServer', x=-164.41, y=19.00, z=308.72], EntityBat['Bat'/325, l='MpServer', x=-165.47, y=19.00, z=310.59], EntityBat['Bat'/326, l='MpServer', x=-155.59, y=20.42, z=308.94], EntityBat['Bat'/327, l='MpServer', x=-160.31, y=43.94, z=304.44], EntityCreeper['Creeper'/583, l='MpServer', x=-260.50, y=21.00, z=320.50], EntityCreeper['Creeper'/335, l='MpServer', x=-146.91, y=64.00, z=252.31], EntityCreeper['Creeper'/3663, l='MpServer', x=-258.50, y=21.00, z=319.50], EntityCreeper['Creeper'/336, l='MpServer', x=-151.50, y=21.00, z=303.50], EntitySkeleton['Skeleton'/625, l='MpServer', x=-269.50, y=46.00, z=281.50], EntityCow['Cow'/147, l='MpServer', x=-302.06, y=68.00, z=239.09], EntityCow['Cow'/148, l='MpServer', x=-290.50, y=72.00, z=249.50], EntityCow['Cow'/149, l='MpServer', x=-292.13, y=72.00, z=248.50], EntityCow['Cow'/150, l='MpServer', x=-301.63, y=74.00, z=248.47], EntityPig['Pig'/151, l='MpServer', x=-290.50, y=72.00, z=255.50], EntityPig['Pig'/152, l='MpServer', x=-289.53, y=71.00, z=252.50], EntityPig['Pig'/153, l='MpServer', x=-290.50, y=72.00, z=255.50], EntityPig['Pig'/154, l='MpServer', x=-288.88, y=71.00, z=249.94], EntitySheep['Sheep'/155, l='MpServer', x=-295.50, y=72.00, z=250.22], EntitySheep['Sheep'/156, l='MpServer', x=-295.50, y=72.00, z=253.50], EntitySheep['Sheep'/157, l='MpServer', x=-295.50, y=72.00, z=251.81], EntitySheep['Sheep'/158, l='MpServer', x=-294.28, y=72.00, z=250.72], EntityRabbit['Rabbit'/159, l='MpServer', x=-291.50, y=72.00, z=259.50], EntityRabbit['Rabbit'/160, l='MpServer', x=-292.50, y=72.00, z=259.50], EntityRabbit['Rabbit'/161, l='MpServer', x=-293.50, y=72.00, z=258.50], EntityZombieVillager['Villager Zombie'/163, l='MpServer', x=-299.50, y=33.00, z=364.50], EntityZombieVillager['Villager Zombie'/164, l='MpServer', x=-297.50, y=33.00, z=365.50], EntityBat['Bat'/165, l='MpServer', x=-294.38, y=52.00, z=364.38], EntityCow['Cow'/172, l='MpServer', x=-277.22, y=72.00, z=257.53], EntityCow['Cow'/173, l='MpServer', x=-278.44, y=73.00, z=255.63], EntityCow['Cow'/174, l='MpServer', x=-279.63, y=74.00, z=254.59], EntityCow['Cow'/175, l='MpServer', x=-278.50, y=75.00, z=262.50], EntityCow['Cow'/176, l='MpServer', x=-277.66, y=65.00, z=295.47], EntityCow['Cow'/177, l='MpServer', x=-276.06, y=65.00, z=294.47], EntityCow['Cow'/178, l='MpServer', x=-278.81, y=64.00, z=296.47], EntityCow['Cow'/179, l='MpServer', x=-276.41, y=65.00, z=296.34], EntityPig['Pig'/180, l='MpServer', x=-278.50, y=65.00, z=317.50], EntityPig['Pig'/181, l='MpServer', x=-278.22, y=64.00, z=313.22], EntityPig['Pig'/182, l='MpServer', x=-279.81, y=64.00, z=314.81], EntityPig['Pig'/183, l='MpServer', x=-278.50, y=65.00, z=317.50], EntityCow['Cow'/184, l='MpServer', x=-272.25, y=66.00, z=320.50], EntityCow['Cow'/185, l='MpServer', x=-275.50, y=67.00, z=327.50], EntityCow['Cow'/186, l='MpServer', x=-272.53, y=67.00, z=332.69], EntityCow['Cow'/187, l='MpServer', x=-280.22, y=66.00, z=326.50], EntitySkeleton['Skeleton'/195, l='MpServer', x=-258.50, y=47.00, z=277.50], EntityCreeper['Creeper'/196, l='MpServer', x=-256.50, y=39.00, z=320.50], EntityBat['Bat'/197, l='MpServer', x=-260.50, y=39.10, z=322.59], EntityCow['Cow'/198, l='MpServer', x=-256.47, y=81.00, z=364.47], EntityCow['Cow'/199, l='MpServer', x=-256.38, y=82.00, z=365.97], EntityCow['Cow'/200, l='MpServer', x=-264.75, y=79.00, z=356.31], EntityBat['Bat'/202, l='MpServer', x=-246.42, y=41.00, z=261.83], EntitySkeleton['Skeleton'/203, l='MpServer', x=-240.53, y=37.00, z=276.84], EntityBat['Bat'/204, l='MpServer', x=-245.91, y=23.47, z=294.36], EntityCreeper['Creeper'/205, l='MpServer', x=-241.50, y=41.00, z=303.50], EntityCreeper['Creeper'/206, l='MpServer', x=-241.44, y=42.00, z=308.01], EntityCreeper['Creeper'/207, l='MpServer', x=-251.97, y=39.00, z=325.63], EntityClientPlayerMP['KrazyMan101'/463, l='MpServer', x=-222.08, y=62.62, z=303.68], EntityCow['Cow'/208, l='MpServer', x=-245.22, y=79.00, z=368.63], EntitySkeleton['Skeleton'/468, l='MpServer', x=-226.06, y=13.00, z=291.47], EntityCreeper['Creeper'/469, l='MpServer', x=-257.50, y=31.00, z=282.50], EntityCreeper['Creeper'/471, l='MpServer', x=-258.50, y=31.00, z=285.50], EntityCreeper['Creeper'/472, l='MpServer', x=-257.50, y=31.00, z=284.50], EntityCreeper['Creeper'/473, l='MpServer', x=-212.50, y=16.00, z=277.50], EntityZombieVillager['Villager Zombie'/474, l='MpServer', x=-250.47, y=21.00, z=291.53], EntitySkeleton['Skeleton'/475, l='MpServer', x=-258.50, y=47.00, z=278.50], EntitySkeleton['Skeleton'/220, l='MpServer', x=-235.09, y=28.00, z=265.53], EntityZombie['Zombie'/221, l='MpServer', x=-234.50, y=38.00, z=269.50], EntityCreeper['Creeper'/478, l='MpServer', x=-210.50, y=16.00, z=277.50], EntityCreeper['Creeper'/222, l='MpServer', x=-237.06, y=38.00, z=269.44], EntityZombie['Zombie'/223, l='MpServer', x=-233.53, y=11.00, z=276.28], EntityCreeper['Creeper'/479, l='MpServer', x=-209.50, y=15.00, z=285.03], EntityZombie['Zombie'/224, l='MpServer', x=-234.09, y=11.00, z=277.44], EntityBat['Bat'/225, l='MpServer', x=-240.01, y=18.33, z=289.83], EntitySquid['Squid'/226, l='MpServer', x=-223.49, y=55.00, z=288.51], EntityBat['Bat'/227, l='MpServer', x=-239.75, y=24.10, z=294.75], EntitySkeleton['Skeleton'/228, l='MpServer', x=-233.44, y=36.00, z=300.06], EntitySkeleton['Skeleton'/229, l='MpServer', x=-231.69, y=35.00, z=296.69], EntityZombie['Zombie'/230, l='MpServer', x=-230.84, y=36.00, z=295.88], EntityZombie['Zombie'/231, l='MpServer', x=-233.03, y=36.00, z=294.50], EntitySkeleton['Skeleton'/232, l='MpServer', x=-238.50, y=33.00, z=288.50], EntitySkeleton['Skeleton'/233, l='MpServer', x=-241.24, y=39.00, z=301.41], EntityBat['Bat'/234, l='MpServer', x=-238.48, y=39.00, z=292.18], EntitySquid['Squid'/235, l='MpServer', x=-235.59, y=55.03, z=291.74], EntitySkeleton['Skeleton'/245, l='MpServer', x=-208.50, y=24.00, z=234.50], EntitySkeleton['Skeleton'/246, l='MpServer', x=-208.50, y=24.00, z=235.50], EntitySkeleton['Skeleton'/247, l='MpServer', x=-218.50, y=33.00, z=237.50], EntityCow['Cow'/248, l='MpServer', x=-220.47, y=72.00, z=253.38], EntityCow['Cow'/249, l='MpServer', x=-208.28, y=69.00, z=245.50], EntityPluckableChicken['entity.Pluckable Chicken.name'/250, l='MpServer', x=-209.22, y=62.32, z=259.81], EntitySheep['Sheep'/251, l='MpServer', x=-214.53, y=64.00, z=264.75], EntitySheep['Sheep'/252, l='MpServer', x=-214.09, y=65.00, z=261.47], EntityCreeper['Creeper'/253, l='MpServer', x=-220.44, y=33.00, z=286.56], EntitySquid['Squid'/254, l='MpServer', x=-212.50, y=60.31, z=272.50], EntitySquid['Squid'/255, l='MpServer', x=-213.49, y=60.00, z=275.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 264923392 bytes (252 MB) / 687144960 bytes (655 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D8 59 mods loaded, 59 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	OpenEye{0.8} [OpenEye] (OpenEye-1.7.10-0.8.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (Gilded-Games-Util-1.7.10.jar) 
	UCHIJAAAA	movillages{1.4.2} [Mo' Villages] ([1.7.10]MoVillages-1.4.2.jar) 
	UCHIJAAAA	aether{1.7.10-1.6} [Aether II] (Aether-2-1.7.10.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	antiqueatlas{4.4.4} [Antique Atlas] (antiqueatlas-1.7.10-4.4.4.jar) 
	UCHIJAAAA	aquacreeper{1.0.1} [Aqua Creeper] (AquaCreepers-1.0.1.jar) 
	UCHIJAAAA	AutoSapling{1.0} [AutoSapling] (AutoSapling-1.1.jar) 
	UCHIJAAAA	backlytra{1.7.10-0.0.3} [Backlytra] (Backlytra-1.7.10-0.0.3 (1).jar) 
	UCHIJAAAA	BetterAchievements{0.1.0} [Better Achievements] (Better-Achievements-Mod-1.7.10.jar) 
	UCHIJAAAA	bettervillages{0.3} [Better Villages Mod] (Better-Villages-Mod-1.7.10.jar) 
	UCHIJAAAA	BWG4{1.2.1} [Better World Generation 4] (Better-World-Generation-4-Mod-1.7.10.jar) 
	UCHIJAAAA	bookshelf{1.0.4.187} [Bookshelf] (Bookshelf-1.7.10-1.0.4.187.jar) 
	UCHIJAAAA	betterboat{1.1.0} [Better Boat] (BetterBoat-1.7.10-1.1.0.jar) 
	UCHIJAAAA	betterplacement{MC1.7.10-1.0.0-1} [Better Placement] (BetterPlacement-MC1.7.10-1.0.0-1.jar) 
	UCHIJAAAA	betterquesting{2.0.233} [Better Questing] (BetterQuesting-2.0.233.jar) 
	UCHIJAAAA	bettervanilla{1.1.1} [BetterVanilla] (BetterVanilla-1.7.10-1.1.1.jar) 
	UCHIJAAAA	brewingapi{1.2.0} [Brewing-API] (Brewing-API-1.7.2-1.2.0.jar) 
	UCHIJAAAA	carvablepumpkins{1.1} [carvablepumpkins] (Carvable-Pumpkins-Mod-1.7.10.jar) 
	UCHIJAAAA	chameleoncreepers{1.4.1} [Chameleon Creepers] (ChameleonCreepers-1.7.10-1.4.1.jar) 
	UCHIJAAAA	craftablehorsearmour{1.1} [Craftable Horse Armour [CHA&S]] (Craftable-Horse-Armour-and-Saddle-Mod-1.7.10.jar) 
	UCHIJAAAA	creativecore{1.3.14} [CreativeCore] (CreativeCore-1.7.10.jar) 
	UCHIJAAAA	DeeperCaves{1.0.0} [DeeperCaves] (DeeperCaves-1.0.0-mc1.7.10.jar) 
	UCHIJAAAA	DisenchanterMod{1.5} [Disenchanter] (DisenchanterMod-[1.7.10]1.5.jar) 
	UCHIJAAAA	etfuturum{1.5.5} [Et Futurum] (Et Futurum-1.5.5.jar) 
	UCHIJAAAA	fbp{2.2.3} [Fancy Block Particles] (FancyBlockParticles-1.7.10-2.2.3.jar) 
	UCHIJAAAA	farseek{2.0.1} [Farseek] (Farseek-1.7.10-2.0.1.jar) 
	UCHIJAAAA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJAAAA	forgecreeperheal{1.1.1} [Forge Creeper Heal 1.1.1] (Forge-Creeper-Heal-Mod-1.7.10.jar) 
	UCHIJAAAA	GlobalGameRules{{}} [Global GameRules] (GlobalGameRules-1.0.jar) 
	UCHIJAAAA	HardcoreDarkness{1.7} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.7.jar) 
	UCHIJAAAA	HardcoreEnderExpansion{1.8.6} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.6.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChun-Util-Mod-1.7.10.jar) 
	UCHIJAAAA	malisiscore{1.7.10-0.14.3} [MalisisCore] (malisiscore-1.7.10-0.14.3 (1).jar) 
	UCHIJAAAA	malisisdoors{1.7.10-1.13.2} [Malisis' Doors] (malisisdoors-1.7.10-1.13.2 (3).jar) 
	UCHIJAAAA	battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (Mine-Blade-Battlegear-2-Mod-1.7.10.jar) 
	UCHIJAAAA	MobProperties{1.0.2} [Mob Properties] (MobProperties-1.7.10-1.0.2.jar) 
	UCHIJAAAA	questbook{2.1.0-1.7.10} [Better Questing Quest Book] (questbook-2.1.0-1.7.10.jar) 
	UCHIJAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJAAAA	redgear_core{2.1.3} [Red Gear Core] (RedGearCore-1.7.10-2.1.3.jar) 
	UCHIJAAAA	redgear_snowfall{2.2.2} [Snowfall] (Snowfall-1.7.10-2.2.2.jar) 
	UCHIJAAAA	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UCHIJAAAA	SpecialAI{1.1.2} [Special AI] (SpecialAI-1.7.10-1.1.2.jar) 
	UCHIJAAAA	bq_standard{2.0.130} [Standard Expansion] (StandardExpansion-2.0.130.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	StartingInventory{1.7.10.r03} [StartingInventory] (Starting-Inventory-Mod-1.7.10.jar) 
	UCHIJAAAA	streams{0.3.3} [Streams] (Streams-1.7.10-0.3.3.jar) 
	UCHIJAAAA	axetomahawk.core{1.4.5.2-1.7.10} [Tomahawks Core] (Tomahawk-Mod-1.7.10.jar) 
	UCHIJAAAA	axetomahawk{1.4.5.2-1.7.10} [Tomahawks] (Tomahawk-Mod-1.7.10.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (Twilight-Forest-Mod-1.7.10.jar) 
	UCHIJAAAA	uncraftingTable{1.4.4} [Uncrafting Table] (Uncrafting-Table-Mod-1.7.10.jar) 
	UCHIJAAAA	VillageNames{1.7.10-1.1a} [Village Names] (VillageNames-1.7.10-1.1a (2).jar) 
	UCHIJAAAA	XaeroMinimap{1.13.4} [Xaero's Minimap] (Xaeros_Minimap_1.13.4_Forge_1.7.10.jar) 
	UCHIJAAAA	XaeroWorldMap{1.1} [Xaero's World Map] (XaerosWorldMap_1.1_Forge_1.7.10.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 780/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [The Skin.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Nicholas32704** [comment]
It still happens even with Animation API uninstalled.

**Comment by exaskye** [comment]
Hm. I don't really see any other potentially bad coremods in the list, and since it also happens with Aether gloves I doubt it's on my end. Something is causing mod render handlers to get called a second time with different transformations.

**Comment by Nicholas32704** [comment]
Could it be an OptiFine glitch?

**Comment by Nicholas32704** [comment]
nvm it still happens with OptiFine uninstalled.

**Comment by Nicholas32704** [comment]
Oh wait I fixed it! Apparently it was the Aether and GildedGamesUtil all along! Works like a charm now.
